# Generated by Django 4.2.28 on 2026-03-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [

        # ============================================================
        # Add payment tracking fields to Order
        # ============================================================

        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('unpaid', 'Unpaid'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed'),
                    ('refunded', 'Refunded')
                ],
                default='unpaid',
                max_length=20
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(
                blank=True,
                max_length=255
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(
                blank=True,
                max_length=255
            ),
        ),

        # ============================================================
        # Add merchant field to OrderItem
        # ============================================================

        migrations.AddField(
            model_name='orderitem',
            name='merchant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sold_order_items',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # ============================================================
        # Update order status field
        # ============================================================

        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('confirmed', 'Confirmed'),
                    ('shipped', 'Shipped'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled')
                ],
                default='pending',
                max_length=20
            ),
        ),

        # ============================================================
        # Fix product FK in OrderItem
        # ============================================================

        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='order_items',
                to='marketplace.product'
            ),
        ),
    ]