# Generated by Django 4.2.28 on 2026-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='address_line1',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='shopperprofile',
            old_name='address_line1',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='delivery_notes',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='county',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos/'),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='county',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='shopper_profiles/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shopperprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
