# Generated by Django 4.2.28 on 2026-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_address_line1_merchantprofile_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shopper', 'Shopper'), ('merchant', 'Merchant')], default='shopper', max_length=20),
        ),
    ]
